default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Facebookcloneapp_development
test:
  <<: *default
  database: Facebookcloneapp_test
production:
  <<: *default
  database: Facebookcloneapp_production
  username: Facebookcloneapp
  password: <%= ENV['FACEBOOKCLONEAPP_DATABASE_PASSWORD'] %>
